version: '3'

services:
  db:
    container_name: postgres_db
    # restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: go_anon

  # server:
  #   container_name: go_server
  #   # restart: always
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     ENVIRONMENT: prod
  #   depends_on:
  #     - db

# docker exec -it postgres_db psql -U postgres-d go_anon
